apiVersion: v1
kind: Secret
metadata:
  name: storage-configuration
type: Opaque
stringData:
  config.env: |-
    export MINIO_ROOT_USER="minio"
    export MINIO_ROOT_PASSWORD="{{ .Values.rootPassword }}"
    export MINIO_STORAGE_CLASS_enc-ext4-az-disk="EC:8"
    export MINIO_BROWSER="on"
