apiVersion: v1
kind: Secret
metadata:
  name: mm-postgres-connection
type: Opaque
stringData:
  DB_CONNECTION_CHECK_URL: postgres://{{ .Values.global.mmUser }}:replaceme@{{ .Values.global.teamId}}-mattermost-sql-cluster:5432/{{ .Values.global.dbName }}
  DB_CONNECTION_STRING: postgres://{{ .Values.global.mmUser }}:replaceme@{{ .Values.global.teamId }}-mattermost-sql-cluster:5432/{{ .Values.global.dbName }}
  MM_SQLSETTINGS_DATASOURCEREPLICAS: postgres://{{ .Values.global.mmUser }}:replaceme@{{ .Values.global.teamId }}-mattermost-sql-cluster:5432/{{ .Values.global.dbName }}
