apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: enc-ext4-az-disk
  annotations:
    "storageclass.kubernetes.io/is-default-class": "{{ .Values.isDefault }}"
provisioner: azuredisk.csi.confidential.cloud
parameters:
  skuName: {{ .Values.skuName }}
  csi.storage.k8s.io/fstype: ext4
reclaimPolicy: Delete
volumeBindingMode: {{ .Values.bindingMode }}
