# Secret to allow postgres cluster to speak to backup minio container.
apiVersion: v1
kind: Secret
metadata:
  name: minio-backup-secret
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: {{ .Values.global.backupAccessId }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.global.backupAccessSecret }}
