apiVersion: v2
name: mm-infra
description: A Helm chart to deploy all infra-style components that need to be deployed once for mattermost to be deployed.
type: application
version: 0.1.0
appVersion: "1.16.0"

dependencies:
  - name: postgres-operator
    version: "1.8.2"
    repository: "https://opensource.zalando.com/postgres-operator/charts/postgres-operator"
    condition: postgresOperator.enabled
  - name: postgres-operator-ui
    version: "1.8.2"
    repository: "https://opensource.zalando.com/postgres-operator/charts/postgres-operator-ui"
    condition: postgresOperator.enabled
  - name: cert-manager
    version: "1.9.1"
    repository: "https://charts.jetstack.io"
    condition: certManager.enabled
  - name: ingress-nginx
    version: "4.2.5"
    repository: "https://kubernetes.github.io/ingress-nginx"
    condition: ingressNginx.enabled
  - name: azuredisk-csi-driver
    version: "1.0.0"
    repository: "https://raw.githubusercontent.com/edgelesssys/constellation-azuredisk-csi-driver/develop/charts/edgeless"
    condition: azurediskCsiDriver.enabled
  - name: encrypted-az-disk
    version: "0.1.0"
    condition: azurediskCsiDriver.enabled
  - name: external-dns
    version: "0.1.0"
    condition: certManager.enabled
    # TODO: Use official mattermost-operator chart https://github.com/mattermost/mattermost-helm/tree/master/charts/mattermost-operator.
  - name: mattermost-operator
    version: "0.1.0"
    condition: mattermostOperator.enabled
